# Site settings
title: 薛尧
description: 简历中心
favicon: /assets/img/avatar.png
baseurl:  #http://resume.xueyao.org
url:  #http://resume.xueyao.org
rss_url: /pages/atom.xml
google_analytics: #UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 薛尧
  title: PHP Developer
  address: 上海, 中国
  email: yaoxue2014@gmail.com
  link: #http://ddbullfrog.com
  weibo:
  github: flowstone
  linkedin: flowstone #ddbullfrog
  twitter: yaoxue2014
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
## 工作经历
  workHistory:
    - work1:
      company: 苏州仁创信息科技有限公司
      location: 苏州, 中国
      title: PHP Developer
      started: 2017
      duration: (2016.01 - 2017.03)
      description:
    - work2:
      company: 苏州聚尚网络科技有限公司
      location: 苏州, 中国
      title: PHP Developer
      started: 2015
      duration: (2015.06 - 2015.12)
      description:
## 项目经历
  projectHistory:
    - project1:
      projectname: 苏易购商城
      company: 苏州仁创信息科技有限公司
      location: 苏州, 中国
      started: 2017
      duration: (2016.08 - 2017.03)
      description: 项目描述：
                   本项目功能包括商品管理、订单管理、会员管理、留言管理、权限管理、系统管理。

                   责任描述：
                   1、参与了商城前期分析，业务模块的划分，数据库表的设计；
                   2、负责用户注册、商品管理、留言评价模块的功能代码实现；
    - project2:
      projectname: 莆树商城
      company: 苏州仁创信息科技有限公司
      location: 苏州, 中国
      started: 2016
      duration: (2016.02 - 2016.07)
      description: 项目描述：
                   项目功能主要包括：注册、登录模块、商品模块购物车模块、支付模块、留言评价模块、用户中心模块、商品管理、订单管理、会员管理、留言管理、权限管理、系统管理。

                   责任描述：
                   1、	参与了商城前期分析，业务模块的划分；
                   2、	负责注册、登录模块、商品管理；

    - project3:
      projectname: 姑苏网上商城
      company: 苏州聚尚网络科技有限公司
      location: 苏州, 中国
      started: 2015
      duration: (2015.09 - 2015.12)
      description: 项目描述：
                   项目功能主要包括：注册、登录模块、商品模块购物车模块、支付模块、留言评价模块、用户中心模块、商品管理、订单管理、会员管理、留言管理、权限管理、系统管理。

                   责任描述：
                   1、参与了商城前期分析，业务模块的划分，数据库表的设计；
                   2、前台主要负责注册、登录模块、留言评价模块的功能代码实现；
                   3、后台主要负责商品管理、留言管理模块的功能代码的实现；

    - project4:
      projectname: 神元生物手机站
      company: 苏州聚尚网络科技有限公司
      location: 苏州, 中国
      started: 2015
      duration: (2015.06 - 2015.08)
      description: 项目描述：
                   本项目使用thinkphp开源项目开发的企业网站，主要包括文章的管理、分类的管理、搜索功能等功能。

                   责任描述：
                   1、负责前期分析，业务模块划分；
                   2、通过全文索引工具xunSearch(迅搜)实现文章的搜索功能；


## 教育经历
  educationHistory:
    - education1:
      organization: 苏州大学
      location: 苏州, 中国
      degree: 本科
      major: 计算机信息管理
      started: 2014
      duration: (2014 - 2016)
      description: 通过课外时间，参加了苏州大学自考并顺利获得本科学士学位，主修计算机网络原理、操作系统概论、数据结构导论、C++程序设计、信息资源管理等13门科目。
    - education2:
      organization: 苏州工业园区服务外包职业学院
      location: 苏州, 中国
      degree: 专科
      major: 嵌入式技术与应用(移动互联网方向)
      started: 2012
      duration: (2012 - 2015)
      description: 主修Java、Android、PHP、网页设计(HTML+JS+CSS)、Flash(ActionScript3.0)，并担任计算机专业相关(所有)科目课代表。
## 语言技能
  languages:
    - language1:
      name: Chinese
      proficiency: 精通
    - language2:
      name: English
      proficiency: 一般
## 编程技术
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 60%
    - skill3:
      name: JavaScript
      percentage: 50%
    - skill4:
      name: AJAX
      percentage: 50%
    - skill5:
      name: Java/C
      percentage: 40%
    - skill6:
      name: PHP+MySQL
      percentage: 80%
    - skill7:
      name: Linux
      percentage: 50%
    - skill8:
      name: 缓存技术(Memcache/redis)
      percentage: 60%
    - skill9:
      name: DeDeCMS/PHPCMS/EmpireCMS
      percentage: 70%
    - skill10:
      name: Git
      percentage: 70%
## 奖励及荣誉
  awards:
      - award1:
        name: 获得2012-2013学年学院二等奖学金
      - award2:
        name: 获得2013-2014学年学院三等奖学金
      - award3:
        name: 获得第四届蓝桥杯江苏赛区Java组二等奖
      - award3:
        name: 全国计算机等级考试四级网络工程师